parameters:
- name: srcPath
  type: string
  default: '.'
- name: runStaticAnalysis
  type: boolean
  default: False
- name: builddir
  type: string
  default: 'procdump_build'
- name: ldpath
  type: string
  default: ''  

steps:
- script: |
    if [ -n "${{ parameters.ldpath }}" ]; then
        export LD_LIBRARY_PATH="${{ parameters.ldpath }}:$LD_LIBRARY_PATH"
    fi
    
    mkdir -p ${{ parameters.srcPath }}/${{ parameters.builddir }} && cd ${{ parameters.srcPath }}/${{ parameters.builddir }}
    cmake ..
    make
  displayName: "Build ProcDump binaries"
